version: '2'

services:
  node:
    build: .
    volumes:
      - .:/usr/src/app
    ports:
      - "3030:3030"
    links:
      - mysql

  mysql:
    image: mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=mydb
      - MYSQL_USER=robert
      - MYSQL_PASSWORD=robert
      - MYSQL_ROOT_PASSWORD=root
